name: Build for Linux

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List directory contents for debugging
      run: |
        ls -la
        pwd

    - name: Install SFML and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libsfml-dev

    - name: Clean build directory if it exists
      run: rm -rf build || true

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release
